# Generated by Django 4.2.7 on 2024-01-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contacts_donuts_recipies_testimonials_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
