# Generated by Django 4.2.7 on 2024-01-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image_post_venue_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Donuts',
        ),
        migrations.DeleteModel(
            name='Recipies',
        ),
        migrations.DeleteModel(
            name='Testimonials',
        ),
        migrations.RemoveField(
            model_name='post',
            name='venue_image',
        ),
    ]
